version: "2"
services:
  influxdb:
    restart: always
    image: hypriot/rpi-influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      # Data persistency
      # sudo mkdir -p /var/influxdb/data
      - /var/influxdb/data:/data

  telegraf:
    restart: always
    image: easypi/telegraf-arm:latest
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

  grafana:
    restart: always
    image: fg2it/grafana-armhf:v4.6.3
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    links:
      - influxdb
    volumes:
      - /var/lib/grafana:/var/lib/grafana

  speedtest:
    restart: always
    image: garaemon/speedtest-into-influxdb
    container_name: speedtest
    links:
      - influxdb
    environment:
      # Do not add quotes
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_DATABASE=speedtest
      - INFLUXDB_PORT=8086
      # once for 20minutes
      - SPEEDTEST_FRQUENCY=1200
